services:
  - type: web
    name: ai-os-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.server:create_app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: API_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: VOICE_ENABLED
        sync: false
      - key: DEBUG_MODE
        sync: false
      - key: ENV
        value: production
      - key: PORT
        value: 10000
